# Site Build Settings

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:year/:month/:day/:title/
plugins:             [jekyll-sitemap, jekyll-seo-tag]

# Customize atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		         'Connex eCommerce'
description:	     'An eCommerce Technology Blog'
author:              'Connex eCommerce'
